plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "test/dummy/db/schema.rb"
    - "test/dummy/app/tools/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/dummy/db/schema.rb"
    - "ciaobrowser.gemspec"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
